In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('data/gfmt_sleep.csv', na_values='*')
df['insomnia'] = df['sci'] <=16

df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2,True
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7,True
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3,True
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20,True
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12,True

In [4]:
grouped = df.groupby('insomnia')

# Take a look
grouped

In [16]:
df_median = grouped.median(grouped)

# Take a look
df_median

,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
insomnia,,,,,,,,,,,,,,
False,54.0,36.0,90.0,80.0,85.0,74.5,55.5,71.5,59.0,75.0,59.25,26.0,4.0,6.0
True,46.0,39.0,90.0,75.0,75.0,76.5,72.0,71.0,68.5,77.0,65.00,14.0,9.0,7.0

In [17]:
df_median.reset_index()

,insomnia,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
0,False,54.0,36.0,90.0,80.0,85.0,74.5,55.5,71.5,59.0,75.0,59.25,26.0,4.0,6.0
1,True,46.0,39.0,90.0,75.0,75.0,76.5,72.0,71.0,68.5,77.0,65.00,14.0,9.0,7.0

In [18]:
df_median = df_median.reset_index()

In [19]:
df.groupby(['gender', 'insomnia']).median().reset_index()

,gender,insomnia,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,rank grouped by insomnia
0,f,False,58.0,36.0,85.0,80.0,85.00,74.00,55.00,70.50,60.00,74.00,58.75,26.0,4.0,7.0,41.00
1,f,True,46.0,39.0,80.0,75.0,72.50,76.50,73.75,71.00,68.50,77.00,70.50,14.0,9.0,7.0,11.00
2,m,False,41.0,38.5,90.0,80.0,82.50,76.00,57.75,74.25,54.75,76.25,59.25,29.0,3.0,6.0,36.25
3,m,True,55.5,37.0,95.0,82.5,83.75,83.75,55.50,75.75,73.25,81.25,62.50,14.0,9.0,8.0,17.50

In [20]:
grouped['percent correct'].rank()

0      11.0
1      21.5
2      23.0
3      19.5
4       3.5
       ...
97     25.0
98     52.5
99     19.0
100    11.5
101     6.5
Name: percent correct, Length: 102, dtype: float64

In [21]:
df['rank grouped by insomnia'] = grouped['percent correct'].rank()

#take a look
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia,rank grouped by insomnia
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2,True,11.0
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7,True,21.5
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3,True,23.0
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20,True,19.5
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12,True,3.5

In [22]:
df_sorted = df.sort_values(by=['insomnia', 'percent correct'])

# look at relevant columns
df_sorted[['insomnia', 'percent correct', 'rank grouped by insomnia']]

    insomnia  percent correct  rank grouped by insomnia
81     False             40.0                       1.0
94     False             55.0                       2.0
39     False             57.5                       3.0
76     False             60.0                       4.5
96     False             60.0                       4.5
..       ...              ...                       ...
1       True             90.0                      21.5
8       True             90.0                      21.5
2       True             92.5                      23.0
11      True             95.0                      24.0
21      True             97.5                      25.0

[102 rows x 3 columns]

In [57]:
def coeff_of_var(data):
    """Compute coefficient of variation from an array of data."""
    print (np.std(data) / np.mean(data))
    return np.std(data) / np.mean(data)

In [58]:
grouped.agg(coeff_of_var)

TypeError: could not convert string to float: 'f'

In [25]:
def ecdf_y(data):
    """ give y-values of an ECDF for an unsorted column in a data frame."""
    return data.rank(method='first') / len(data)

In [26]:
df['ecdf_y grouped by insomnia'] = grouped['percent correct'].transform(ecdf_y)

#look
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia,rank grouped by insomnia,ecdf_y grouped by insomnia
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2,True,11.0,0.44
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7,True,21.5,0.84
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3,True,23.0,0.92
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20,True,19.5,0.76
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12,True,3.5,0.12

In [27]:
df.groupby(['gender', 'insomnia'])['percent correct'].describe()

                 count       mean        std   min     25%    50%     75%  \
gender insomnia
f      False      55.0  82.045455  10.844982  55.0  75.000  85.00  88.750
       True       19.0  73.947368  13.624829  45.0  67.500  72.50  83.750
m      False      22.0  80.000000  12.770875  40.0  77.500  82.50  89.375
       True        6.0  82.916667  10.655593  67.5  76.875  83.75  88.750

                   max
gender insomnia
f      False     100.0
       True       95.0
m      False      95.0
       True       97.5

In [28]:
for name, group in df.groupby(['gender', 'insomnia']):
    print(name, ': ', group['percent correct'].median())

('f', np.False_) :  85.0
('f', np.True_) :  72.5
('m', np.False_) :  82.5
('m', np.True_) :  83.75

In [52]:
df = pd.read_csv('data/reeves_gradient_width_various_methods.csv', comment='#', header=[0,1])
df.head()

           wt                dl1/+; dl-venus/+                          \
  wholemounts cross-sections       anti-Dorsal anti-Venus Venus (live)
0      0.1288         0.1327            0.1482     0.1632       0.1666
1      0.1554         0.1457            0.1503     0.1671       0.1753
2      0.1306         0.1447            0.1577     0.1704       0.1705
3      0.1413         0.1282            0.1711     0.1779          NaN
4      0.1557         0.1487            0.1342     0.1483          NaN

  dl1/+; dl-gfp/+
      anti-Dorsal anti-GFP GFP (live)
0          0.2248   0.2389     0.2412
1          0.1891   0.2035     0.1942
2          0.1705   0.1943     0.2186
3          0.1735   0.2000     0.2104
4          0.2135   0.2560     0.2463

In [53]:
df = pd.melt(df, value_name='gradient width', var_name=['genotype', 'method'])
df.head()

ValueError: var_name=['genotype', 'method'] must be a scalar.

In [37]:
df = df.dropna()

In [48]:
df.columns

Index(['variable_0', 'variable_1', 'gradient width'], dtype='object')

In [54]:
df.groupby(['genotype', 'method']).describe()

KeyError: 'genotype'

In [61]:
%load_ext watermark
%watermark -v -p numpy,pandas,jupyterlab

Python implementation: CPython
Python version       : 3.10.15
IPython version      : 8.29.0

numpy     : 2.0.2
pandas    : 2.2.3
jupyterlab: 4.2.5